## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import G_KEY

# Configure gmaps
gmaps.configure(api_key=G_KEY)

In [47]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_Vacation.csv")
vacation_df.head()
vacation_df = vacation_df.drop_duplicates()
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Kavieng,PG,82.69,light rain,-2.5744,150.7967,Nusa Island Retreat
1,9,Vaini,TO,84.36,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
2,20,Namatanai,PG,83.08,overcast clouds,-3.6667,152.4333,Seagulls Inn Namatani
3,34,Karratha,AU,83.05,broken clouds,-20.7377,116.8463,ibis Styles Karratha
4,79,Haapiti,PF,87.53,overcast clouds,-17.5667,-149.8667,Linareva Moorea Beach Resort

In [50]:
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Kavieng,PG,82.69,light rain,-2.5744,150.7967,Nusa Island Retreat
1,9,Vaini,TO,84.36,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
2,20,Namatanai,PG,83.08,overcast clouds,-3.6667,152.4333,Seagulls Inn Namatani
3,34,Karratha,AU,83.05,broken clouds,-20.7377,116.8463,ibis Styles Karratha
4,79,Haapiti,PF,87.53,overcast clouds,-17.5667,-149.8667,Linareva Moorea Beach Resort
...,...,...,...,...,...,...,...,...
90,1056,Kahului,US,83.46,few clouds,20.8947,-156.4700,Maui Seaside Hotel
91,1060,Acapulco,MX,84.02,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
92,1073,Maumere,ID,80.15,moderate rain,-8.6199,122.2111,Sylvia Hotel
93,1086,Samarai,PG,82.78,scattered clouds,-10.6167,150.6667,Nuli Sapi
94,1089,Kieta,PG,84.02,light rain,-6.2167,155.6333,Uruna Bay Retreat

In [48]:
vacation_df.drop_duplicates()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Kavieng,PG,82.69,light rain,-2.5744,150.7967,Nusa Island Retreat
1,9,Vaini,TO,84.36,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
2,20,Namatanai,PG,83.08,overcast clouds,-3.6667,152.4333,Seagulls Inn Namatani
3,34,Karratha,AU,83.05,broken clouds,-20.7377,116.8463,ibis Styles Karratha
4,79,Haapiti,PF,87.53,overcast clouds,-17.5667,-149.8667,Linareva Moorea Beach Resort
...,...,...,...,...,...,...,...,...
90,1056,Kahului,US,83.46,few clouds,20.8947,-156.4700,Maui Seaside Hotel
91,1060,Acapulco,MX,84.02,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
92,1073,Maumere,ID,80.15,moderate rain,-8.6199,122.2111,Sylvia Hotel
93,1086,Samarai,PG,82.78,scattered clouds,-10.6167,150.6667,Nuli Sapi
94,1089,Kieta,PG,84.02,light rain,-6.2167,155.6333,Uruna Bay Retreat

In [39]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}, Temp: {Max Temp}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [40]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City_ID'] == 3]
vacation_end = vacation_start
vacation_stop1 = vacation_df.loc[vacation_df['City_ID'] == 9]
vacation_stop2 = vacation_df.loc[vacation_df['City_ID'] == 20] 
vacation_stop3 = vacation_df.loc[vacation_df['City_ID'] == 79]

In [60]:
vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Kavieng,PG,82.69,light rain,-2.5744,150.7967,Nusa Island Retreat

In [57]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start.to_numpy()[0][5], vacation_start.to_numpy()[0][6])
end = (vacation_end.to_numpy()[0][5], vacation_end.to_numpy()[0][6])
stop1 = (vacation_stop1.to_numpy()[0][5], vacation_stop1.to_numpy()[0][6])
stop2 = (vacation_stop2.to_numpy()[0][5], vacation_stop2.to_numpy()[0][6])
stop3 = (vacation_stop3.to_numpy()[0][5], vacation_stop3.to_numpy()[0][6])

In [58]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
directions = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3], 
        travel_mode='DRIVING' or 'WALKING' or 'BICYCLING')
fig.add_layer(directions)
fig

Figure(layout=FigureLayout(height='420px'))

In [61]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Kavieng,PG,82.69,light rain,-2.5744,150.7967,Nusa Island Retreat
1,9,Vaini,TO,84.36,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
2,20,Namatanai,PG,83.08,overcast clouds,-3.6667,152.4333,Seagulls Inn Namatani
3,79,Haapiti,PF,87.53,overcast clouds,-17.5667,-149.8667,Linareva Moorea Beach Resort

In [62]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}, Temp: {Max Temp}</dd>
</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [63]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))