In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Create a new set of 2,000 random latitudes and longitudes.

In [2]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [7]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

## Get the nearest city using the citipy module

In [8]:
# Use the citipy module to determine city based on latitude and longitude.
from citipy import citipy

In [9]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

599

## Perform an API call with the OpenWeatherMap.

In [57]:
# Import the requests library.
import requests

# Import the API key.
from config2 import weather_api_key

In [58]:
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=32ed87d75f188355dd9b7c17beaf7933

In [59]:
# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

## Retrieve the following information from the API call:

In [61]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

Beginning Data Retrieval
-----------------------------

In [66]:
city_weather

{'coord': {'lon': -85.8403, 'lat': 49.1215},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04d'}],
 'base': 'stations',
 'main': {'temp': 27.32,
  'feels_like': 17.96,
  'temp_min': 27.32,
  'temp_max': 27.32,
  'pressure': 1007,
  'humidity': 88,
  'sea_level': 1007,
  'grnd_level': 966},
 'visibility': 6829,
 'wind': {'speed': 9.93, 'deg': 186, 'gust': 20.45},
 'clouds': {'all': 100},
 'dt': 1644351467,
 'sys': {'type': 1,
  'id': 185,
  'country': 'CA',
  'sunrise': 1644325432,
  'sunset': 1644360679},
 'timezone': -18000,
 'id': 6065253,
 'name': 'Manitouwadge',
 'cod': 200}

In [67]:
len(city_weather)

13

In [70]:
city_weather.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [71]:
city_weather['weather']

[{'id': 804,
  'main': 'Clouds',
  'description': 'overcast clouds',
  'icon': '04d'}]

In [74]:
len(city_weather['weather'])

1

In [75]:
city_weather['weather'][0]

{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}

In [76]:
city_weather['weather'][0]['description']

'overcast clouds'

In [88]:
# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
      

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
# Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_description = city_weather['weather'][0]['description']
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Country": city_country,
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Current Description": city_description                          ,
                          })

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Processing Record 50 of Set 23 | carnarvon
Processing Record 51 of Set 23 | nikolskoye
Processing Record 52 of Set 23 | fortuna
Processing Record 53 of Set 23 | kavieng
Processing Record 54 of Set 23 | kaitangata
Processing Record 55 of Set 23 | dikson
Processing Record 56 of Set 23 | rikitea
Processing Record 57 of Set 23 | ribeira grande
Processing Record 58 of Set 23 | cidreira
Processing Record 59 of Set 23 | vaini
Processing Record 60 of Set 23 | ushuaia
Processing Record 61 of Set 23 | badnawar
Processing Record 62 of Set 23 | esperance
Processing Record 63 of Set 23 | sitka
Processing Record 64 of Set 23 | cape town
Processing Record 65 of Set 23 | bredasdorp
Processing Record 66 of Set 23 | thompson
Processing Record 67 of Set 23 | nuevo progreso
Processing Record 68 of Set 23 | albany
Processing Record 69 of Set 23 | beian
Processing Record 70 of Set 23 | namatanai
Processing Record 71 of Set 23 | taolanaro
City not found. Skipping...
Processing Record 72 of Set 23 | qaanaaq
Processing Record 73 of Set 23 | honningsvag
Processing Record 74 of Set 23 | tete
Processing Record 75 of Set 23 | hermanus
Processing Record 76 of Set 23 | upernavik
Processing Record 77 of Set 23 | illoqqortoormiut
City not found. Skipping...
Processing Record 78 of Set 23 | chicama
Processing Record 79 of Set 23 | barentsburg
City not found. Skipping...
Processing Record 80 of Set 23 | kiunga
Processing Record 81 of Set 23 | tumannyy
City not found. Skipping...
Processing Record 82 of Set 23 | macaboboni
City not found. Skipping...
Processing Record 83 of Set 23 | beloha
Processing Record 84 of Set 23 | mahebourg
Processing Record 85 of Set 23 | saskylakh
Processing Record 86 of Set 23 | new norfolk
Processing Record 87 of Set 23 | idritsa
Processing Record 88 of Set 23 | japura
Processing Record 89 of Set 23 | karratha
Processing Record 90 of Set 23 | tasiilaq
Processing Record 91 of Set 23 | busselton
Processing Record 92 of Set 23 | tuatapere
Processing Record 93 of Set 23 | san martin
Processing Record 94 of Set 23 | inirida
Processing Record 95 of Set 23 | acari
Processing Record 96 of Set 23 | castro
Processing Record 97 of Set 23 | havre-saint-pierre
Processing Record 98 of Set 23 | san juan
Processing Record 99 of Set 23 | toliary
City not found. Skipping...
Processing Record 1 of Set 24 | atuona
Processing Record 2 of Set 24 | sao joao da barra
Processing Record 3 of Set 24 | antalaha
Processing Record 4 of Set 24 | naze
Processing Record 5 of Set 24 | tuktoyaktuk
Processing Record 6 of Set 24 | basco
Processing Record 7 of Set 24 | siocon
Processing Record 8 of Set 24 | belushya guba
City not found. Skipping...
Processing Record 9 of Set 24 | east london
Processing Record 10 of Set 24 | punta arenas
Processing Record 11 of Set 24 | mataura
Processing Record 12 of Set 24 | barrow
Processing Record 13 of Set 24 | jever
Processing Record 14 of Set 24 | havelock
Processing Record 15 of Set 24 | pisco
Processing Record 16 of Set 24 | rogun
City not found. Skipping...
Processing Record 17 of Set 24 | cabo san lucas
Processing Record 18 of Set 24 | boende
Processing Record 19 of Set 24 | olafsvik
Processing Record 20 of Set 24 | samusu
City not found. Skipping...
Processing Record 21 of Set 24 | gao
Processing Record 22 of Set 24 | talnakh
Processing Record 23 of Set 24 | hilo
Processing Record 24 of Set 24 | hobart
Processing Record 25 of Set 24 | jamestown
Processing Record 26 of Set 24 | clyde river
Processing Record 27 of Set 24 | mocambique
City not found. Skipping...
Processing Record 28 of Set 24 | qena
Processing Record 29 of Set 24 | wilmington
Processing Record 30 of Set 24 | fairbanks
Processing Record 31 of Set 24 | port elizabeth
Processing Record 32 of Set 24 | bethel
Processing Record 33 of Set 24 | mys shmidta
City not found. Skipping...
Processing Record 34 of Set 24 | ust-maya
Processing Record 35 of Set 24 | xining
Processing Record 36 of Set 24 | nizhneyansk
City not found. Skipping...
Processing Record 37 of Set 24 | ilulissat
Processing Record 38 of Set 24 | marcona
City not found. Skipping...
Processing Record 39 of Set 24 | bilibino
Processing Record 40 of Set 24 | puerto ayora
Processing Record 41 of Set 24 | matay
Processing Record 42 of Set 24 | port augusta
Processing Record 43 of Set 24 | haapiti
Processing Record 44 of Set 24 | chuy
Processing Record 45 of Set 24 | kurilsk
Processing Record 46 of Set 24 | taman
Processing Record 47 of Set 24 | airai
Processing Record 48 of Set 24 | coihaique
Processing Record 49 of Set 24 | puerto colombia
Processing Record 50 of Set 24 | souillac
Processing Record 1 of Set 25 | yamaranguila
Processing Record 2 of Set 25 | hithadhoo
Processing Record 3 of Set 25 | mareeba
Processing Record 4 of Set 25 | leningradskiy
Processing Record 5 of Set 25 | aras
Processing Record 6 of Set 25 | progreso
Processing Record 7 of Set 25 | lipin bor
Processing Record 8 of Set 25 | butaritari
Processing Record 9 of Set 25 | katsuura
Processing Record 10 of Set 25 | arraial do cabo
Processing Record 11 of Set 25 | ambunti
Processing Record 12 of Set 25 | road town
Processing Record 13 of Set 25 | lorengau
Processing Record 14 of Set 25 | kirkland lake
Processing Record 15 of Set 25 | port alfred
Processing Record 16 of Set 25 | vila franca do campo
Processing Record 17 of Set 25 | manokwari
Processing Record 18 of Set 25 | burnie
Processing Record 19 of Set 25 | yenagoa
Processing Record 20 of Set 25 | katangli
Processing Record 21 of Set 25 | mar del plata
Processing Record 22 of Set 25 | sentyabrskiy
City not found. Skipping...
Processing Record 23 of Set 25 | kapaa
Processing Record 24 of Set 25 | ostrovnoy
Processing Record 25 of Set 25 | faanui
Processing Record 26 of Set 25 | taoudenni
Processing Record 27 of Set 25 | yellowknife
Processing Record 28 of Set 25 | omboue
Processing Record 29 of Set 25 | tiksi
Processing Record 30 of Set 25 | conceicao do araguaia
Processing Record 31 of Set 25 | durban
Processing Record 32 of Set 25 | berlevag
Processing Record 33 of Set 25 | kavaratti
Processing Record 34 of Set 25 | ixtapa
Processing Record 35 of Set 25 | durant
Processing Record 36 of Set 25 | ngukurr
City not found. Skipping...
Processing Record 37 of Set 25 | richards bay
Processing Record 38 of Set 25 | vestmannaeyjar
Processing Record 39 of Set 25 | narsaq
Processing Record 40 of Set 25 | zhigansk
Processing Record 41 of Set 25 | khatanga
Processing Record 42 of Set 25 | puerto escondido
Processing Record 43 of Set 25 | grand river south east
City not found. Skipping...
Processing Record 44 of Set 25 | rizhao
Processing Record 45 of Set 25 | severo-kurilsk
Processing Record 46 of Set 25 | luwingu
Processing Record 47 of Set 25 | avarua
Processing Record 48 of Set 25 | krasnogvardeyskoye
Processing Record 49 of Set 25 | glenwood springs
Processing Record 50 of Set 25 | la rioja
Processing Record 1 of Set 26 | tilichiki
Processing Record 2 of Set 26 | iqaluit
Processing Record 3 of Set 26 | shimoda
Processing Record 4 of Set 26 | hualmay
Processing Record 5 of Set 26 | pechenga
Processing Record 6 of Set 26 | petrivka
Processing Record 7 of Set 26 | faya
Processing Record 8 of Set 26 | qandahar
City not found. Skipping...
Processing Record 9 of Set 26 | vila velha
Processing Record 10 of Set 26 | kentau
Processing Record 11 of Set 26 | kharan
Processing Record 12 of Set 26 | de aar
Processing Record 13 of Set 26 | provideniya
Processing Record 14 of Set 26 | sangueya
Processing Record 15 of Set 26 | poya
Processing Record 16 of Set 26 | felidhoo
City not found. Skipping...
Processing Record 17 of Set 26 | dandong
Processing Record 18 of Set 26 | longyearbyen
Processing Record 19 of Set 26 | kuche
City not found. Skipping...
Processing Record 20 of Set 26 | vao
Processing Record 21 of Set 26 | bali
Processing Record 22 of Set 26 | saint-pierre
Processing Record 23 of Set 26 | inhambane
Processing Record 24 of Set 26 | monrovia
Processing Record 25 of Set 26 | tazovskiy
Processing Record 26 of Set 26 | qasigiannguit
Processing Record 27 of Set 26 | waingapu
Processing Record 28 of Set 26 | kjopsvik
Processing Record 29 of Set 26 | bosaso
Processing Record 30 of Set 26 | mao
Processing Record 31 of Set 26 | grand-santi

Processing Record 32 of Set 26 | urulga
City not found. Skipping...
Processing Record 33 of Set 26 | bontang
Processing Record 34 of Set 26 | redlands
Processing Record 35 of Set 26 | lompoc
Processing Record 36 of Set 26 | shancheng
Processing Record 37 of Set 26 | along
Processing Record 38 of Set 26 | ossora
Processing Record 39 of Set 26 | bluff
Processing Record 40 of Set 26 | tomigusuku
Processing Record 41 of Set 26 | tsabong
Processing Record 42 of Set 26 | lavrentiya
Processing Record 43 of Set 26 | banda aceh
Processing Record 44 of Set 26 | bandarbeyla
Processing Record 45 of Set 26 | byron bay
Processing Record 46 of Set 26 | salinopolis
Processing Record 47 of Set 26 | wattegama
Processing Record 48 of Set 26 | saint-philippe
Processing Record 49 of Set 26 | safranbolu
Processing Record 50 of Set 26 | lerwick
Processing Record 1 of Set 27 | fevralsk
City not found. Skipping...
Processing Record 2 of Set 27 | santa cruz del sur
Processing Record 3 of Set 27 | ayorou
Processing Record 4 of Set 27 | pochutla
Processing Record 5 of Set 27 | pevek
Processing Record 6 of Set 27 | alofi
Processing Record 7 of Set 27 | celestun
Processing Record 8 of Set 27 | chernyshevskiy
Processing Record 9 of Set 27 | wanaka
Processing Record 10 of Set 27 | geraldton
Processing Record 11 of Set 27 | san patricio
Processing Record 12 of Set 27 | waw
Processing Record 13 of Set 27 | tidore
City not found. Skipping...
Processing Record 14 of Set 27 | moron
Processing Record 15 of Set 27 | dire
Processing Record 16 of Set 27 | okha
Processing Record 17 of Set 27 | mazamari
Processing Record 18 of Set 27 | wladyslawowo
Processing Record 19 of Set 27 | rawson
Processing Record 20 of Set 27 | komsomolskiy
Processing Record 21 of Set 27 | neokhorion
Processing Record 22 of Set 27 | matiri
Processing Record 23 of Set 27 | filadelfia
Processing Record 24 of Set 27 | poitiers
Processing Record 25 of Set 27 | high rock
Processing Record 26 of Set 27 | bima
Processing Record 27 of Set 27 | wabag
Processing Record 28 of Set 27 | laguna
Processing Record 29 of Set 27 | mlonggo
Processing Record 30 of Set 27 | tolbazy
Processing Record 31 of Set 27 | khandagayty
Processing Record 32 of Set 27 | victoria
Processing Record 33 of Set 27 | sao filipe
Processing Record 34 of Set 27 | acarau
Processing Record 35 of Set 27 | christchurch
Processing Record 36 of Set 27 | tabory
Processing Record 37 of Set 27 | hamilton
Processing Record 38 of Set 27 | ambodifototra
City not found. Skipping...
Processing Record 39 of Set 27 | nizwa
Processing Record 40 of Set 27 | mercedes
Processing Record 41 of Set 27 | taylorville
Processing Record 42 of Set 27 | atocha
Processing Record 43 of Set 27 | umzimvubu
City not found. Skipping...
Processing Record 44 of Set 27 | jieshi
Processing Record 45 of Set 27 | ellensburg
Processing Record 46 of Set 27 | kabelvag
Processing Record 47 of Set 27 | bathsheba
Processing Record 48 of Set 27 | bonthe
Processing Record 49 of Set 27 | juegang
Processing Record 50 of Set 27 | guastatoya
Processing Record 1 of Set 28 | sungairaya
Processing Record 2 of Set 28 | port hardy
Processing Record 3 of Set 28 | chokurdakh
Processing Record 4 of Set 28 | muros
Processing Record 5 of Set 28 | nieuw amsterdam
Processing Record 6 of Set 28 | nuevo san juan
Processing Record 7 of Set 28 | astorga
Processing Record 8 of Set 28 | sisimiut
Processing Record 9 of Set 28 | montepuez
Processing Record 10 of Set 28 | bloomfield
Processing Record 11 of Set 28 | palabuhanratu
City not found. Skipping...
Processing Record 12 of Set 28 | yar-sale
Processing Record 13 of Set 28 | najran
Processing Record 14 of Set 28 | aquiraz
Processing Record 15 of Set 28 | kodiak
Processing Record 16 of Set 28 | port lincoln
Processing Record 17 of Set 28 | kruisfontein
Processing Record 18 of Set 28 | maniitsoq
Processing Record 19 of Set 28 | lluta
Processing Record 20 of Set 28 | husavik
Processing Record 21 of Set 28 | lac du bonnet
Processing Record 22 of Set 28 | imeni zhelyabova
Processing Record 23 of Set 28 | patamea
City not found. Skipping...
Processing Record 24 of Set 28 | eureka
Processing Record 25 of Set 28 | salalah
Processing Record 26 of Set 28 | outram
Processing Record 27 of Set 28 | georgetown
Processing Record 28 of Set 28 | sioux lookout
Processing Record 29 of Set 28 | saint andrews
Processing Record 30 of Set 28 | kloulklubed
Processing Record 31 of Set 28 | mount isa
Processing Record 32 of Set 28 | weligama
Processing Record 33 of Set 28 | dingle
Processing Record 34 of Set 28 | flin flon
Processing Record 35 of Set 28 | udachnyy
Processing Record 36 of Set 28 | erzin
Processing Record 37 of Set 28 | kumluca
Processing Record 38 of Set 28 | mega
Processing Record 39 of Set 28 | belyy yar
Processing Record 40 of Set 28 | ambilobe
Processing Record 41 of Set 28 | staritsa
Processing Record 42 of Set 28 | hovd
Processing Record 43 of Set 28 | hervey bay
Processing Record 44 of Set 28 | opuwo
Processing Record 45 of Set 28 | lata
Processing Record 46 of Set 28 | ponta do sol
Processing Record 47 of Set 28 | cockburn town
Processing Record 48 of Set 28 | pacific grove
Processing Record 49 of Set 28 | okhotsk
Processing Record 50 of Set 28 | fare
Processing Record 1 of Set 29 | bahua
Processing Record 2 of Set 29 | la orilla
Processing Record 3 of Set 29 | logan lake
Processing Record 4 of Set 29 | nago
Processing Record 5 of Set 29 | hay river
Processing Record 6 of Set 29 | campina verde
Processing Record 7 of Set 29 | indiana
Processing Record 8 of Set 29 | lebu
Processing Record 9 of Set 29 | slave lake
Processing Record 10 of Set 29 | soimi
Processing Record 11 of Set 29 | ghotki
Processing Record 12 of Set 29 | yinchuan
Processing Record 13 of Set 29 | payakumbuh
Processing Record 14 of Set 29 | usinsk
Processing Record 15 of Set 29 | tuskegee
Processing Record 16 of Set 29 | kazachinskoye
Processing Record 17 of Set 29 | aksu
Processing Record 18 of Set 29 | qaqortoq
Processing Record 19 of Set 29 | cedar city
Processing Record 20 of Set 29 | torbay
Processing Record 21 of Set 29 | loei
Processing Record 22 of Set 29 | tamandare
Processing Record 23 of Set 29 | sesheke
Processing Record 24 of Set 29 | norman wells
Processing Record 25 of Set 29 | vostok
Processing Record 26 of Set 29 | alakurtti
Processing Record 27 of Set 29 | cherskiy
Processing Record 28 of Set 29 | nakhon phanom
Processing Record 29 of Set 29 | belaya gora
Processing Record 30 of Set 29 | flinders
Processing Record 31 of Set 29 | ramgarh
Processing Record 32 of Set 29 | balaipungut
Processing Record 33 of Set 29 | galle
Processing Record 34 of Set 29 | fougamou
Processing Record 35 of Set 29 | novobureyskiy
Processing Record 36 of Set 29 | hofn
Processing Record 37 of Set 29 | naryan-mar
Processing Record 38 of Set 29 | clacton-on-sea
Processing Record 39 of Set 29 | sofiysk
City not found. Skipping...
Processing Record 40 of Set 29 | bowen
Processing Record 41 of Set 29 | jiaojiang
Processing Record 42 of Set 29 | mendahara
City not found. Skipping...
Processing Record 43 of Set 29 | sembe
Processing Record 44 of Set 29 | podor
Processing Record 45 of Set 29 | midland
Processing Record 46 of Set 29 | cayenne
Processing Record 47 of Set 29 | salcininkai
Processing Record 48 of Set 29 | rumonge
Processing Record 49 of Set 29 | phek
Processing Record 50 of Set 29 | yaan
Processing Record 1 of Set 30 | severodvinsk
Processing Record 2 of Set 30 | katobu
Processing Record 3 of Set 30 | bijar
Processing Record 4 of Set 30 | nsoko
Processing Record 5 of Set 30 | talcahuano
Processing Record 6 of Set 30 | olinda
Processing Record 7 of Set 30 | shache
Processing Record 8 of Set 30 | galiwinku
City not found. Skipping...
Processing Record 9 of Set 30 | wausau
Processing Record 10 of Set 30 | guarapari
Processing Record 11 of Set 30 | adrar
Processing Record 12 of Set 30 | brasilia
Processing Record 13 of Set 30 | labrea
Processing Record 14 of Set 30 | ilheus
Processing Record 15 of Set 30 | la ronge
Processing Record 16 of Set 30 | yasnyy
Processing Record 17 of Set 30 | eyl
Processing Record 18 of Set 30 | coahuayana
Processing Record 19 of Set 30 | fort nelson
Processing Record 20 of Set 30 | hutang

Processing Record 21 of Set 30 | touros
Processing Record 22 of Set 30 | mananara
Processing Record 23 of Set 30 | camacha
Processing Record 24 of Set 30 | dolbeau
City not found. Skipping...
Processing Record 25 of Set 30 | saint-francois
Processing Record 26 of Set 30 | gazli
Processing Record 27 of Set 30 | sanming
Processing Record 28 of Set 30 | rawannawi
City not found. Skipping...
Processing Record 29 of Set 30 | vanimo
Processing Record 30 of Set 30 | kutum
Processing Record 31 of Set 30 | sorong
Processing Record 32 of Set 30 | cimislia
Processing Record 33 of Set 30 | shingu
Processing Record 34 of Set 30 | bengkulu
Processing Record 35 of Set 30 | itaituba
Processing Record 36 of Set 30 | marrakesh
Processing Record 37 of Set 30 | los llanos de aridane
Processing Record 38 of Set 30 | caravelas
Processing Record 39 of Set 30 | raposa
Processing Record 40 of Set 30 | saint-augustin
Processing Record 41 of Set 30 | poum
Processing Record 42 of Set 30 | waipawa
Processing Record 43 of Set 30 | batagay-alyta
Processing Record 44 of Set 30 | hearst
Processing Record 45 of Set 30 | lae
Processing Record 46 of Set 30 | avera
Processing Record 47 of Set 30 | burica
City not found. Skipping...
Processing Record 48 of Set 30 | sinaloa
Processing Record 49 of Set 30 | ankazobe
Processing Record 50 of Set 30 | forestville
Processing Record 1 of Set 31 | mekhelta
City not found. Skipping...
Processing Record 2 of Set 31 | pohrebyshche
Processing Record 3 of Set 31 | karkaralinsk
City not found. Skipping...
Processing Record 4 of Set 31 | mugur-aksy
Processing Record 5 of Set 31 | mergui
City not found. Skipping...
Processing Record 6 of Set 31 | matara
Processing Record 7 of Set 31 | asau
Processing Record 8 of Set 31 | magadan
Processing Record 9 of Set 31 | guerrero negro
Processing Record 10 of Set 31 | atar
Processing Record 11 of Set 31 | korla
Processing Record 12 of Set 31 | chara
Processing Record 13 of Set 31 | zhicheng
Processing Record 14 of Set 31 | aosta
Processing Record 15 of Set 31 | palembang
Processing Record 16 of Set 31 | wucheng
Processing Record 17 of Set 31 | dimitrovgrad
Processing Record 18 of Set 31 | nishihara
Processing Record 19 of Set 31 | pimentel
Processing Record 20 of Set 31 | laizhou
Processing Record 21 of Set 31 | davila
Processing Record 22 of Set 31 | batemans bay
Processing Record 23 of Set 31 | lumphat
Processing Record 24 of Set 31 | dodoma
Processing Record 25 of Set 31 | yirol
City not found. Skipping...
Processing Record 26 of Set 31 | bloemfontein
Processing Record 27 of Set 31 | stephenville
Processing Record 28 of Set 31 | nadym
Processing Record 29 of Set 31 | diglur
Processing Record 30 of Set 31 | anori
Processing Record 31 of Set 31 | ancud
Processing Record 32 of Set 31 | maralal
Processing Record 33 of Set 31 | namibe
Processing Record 34 of Set 31 | amderma
City not found. Skipping...
Processing Record 35 of Set 31 | yarkovo
Processing Record 36 of Set 31 | college
Processing Record 37 of Set 31 | ornskoldsvik
Processing Record 38 of Set 31 | kudahuvadhoo
Processing Record 39 of Set 31 | rhede
Processing Record 40 of Set 31 | yumen
Processing Record 41 of Set 31 | ormond beach
Processing Record 42 of Set 31 | yashkul
Processing Record 43 of Set 31 | arroyo
Processing Record 44 of Set 31 | caranavi
Processing Record 45 of Set 31 | fukue
Processing Record 46 of Set 31 | ucluelet
Processing Record 47 of Set 31 | bukachacha
Processing Record 48 of Set 31 | nome
Processing Record 49 of Set 31 | wulanhaote
City not found. Skipping...
Processing Record 50 of Set 31 | bereda
Processing Record 1 of Set 32 | gallup
Processing Record 2 of Set 32 | cap malheureux
Processing Record 3 of Set 32 | hami
Processing Record 4 of Set 32 | inuvik
Processing Record 5 of Set 32 | bargal
City not found. Skipping...
Processing Record 6 of Set 32 | nyurba
Processing Record 7 of Set 32 | blantyre
Processing Record 8 of Set 32 | kanigoro
Processing Record 9 of Set 32 | gradignan
Processing Record 10 of Set 32 | tautira
Processing Record 11 of Set 32 | ibra
Processing Record 12 of Set 32 | povenets
Processing Record 13 of Set 32 | dhidhdhoo
Processing Record 14 of Set 32 | hambantota
Processing Record 15 of Set 32 | aitape
Processing Record 16 of Set 32 | walla walla
Processing Record 17 of Set 32 | kitimat
Processing Record 18 of Set 32 | cascais
Processing Record 19 of Set 32 | inta
Processing Record 20 of Set 32 | beringovskiy
Processing Record 21 of Set 32 | knysna
Processing Record 22 of Set 32 | lagoa
Processing Record 23 of Set 32 | churapcha
Processing Record 24 of Set 32 | ibirama
Processing Record 25 of Set 32 | moose jaw
Processing Record 26 of Set 32 | teberda
Processing Record 27 of Set 32 | ignacio zaragoza
Processing Record 28 of Set 32 | alta floresta
Processing Record 29 of Set 32 | charlestown
Processing Record 30 of Set 32 | alotau
City not found. Skipping...
Processing Record 31 of Set 32 | lincoln
Processing Record 32 of Set 32 | saleaula
City not found. Skipping...
Processing Record 33 of Set 32 | conde
Processing Record 34 of Set 32 | bonavista
Processing Record 35 of Set 32 | saint-joseph
Processing Record 36 of Set 32 | virginia beach
Processing Record 37 of Set 32 | frontera
Processing Record 38 of Set 32 | schleswig
Processing Record 39 of Set 32 | vardo
Processing Record 40 of Set 32 | mehamn
Processing Record 41 of Set 32 | aban
Processing Record 42 of Set 32 | neuquen
Processing Record 43 of Set 32 | satipo
Processing Record 44 of Set 32 | srednekolymsk
Processing Record 45 of Set 32 | sabinopolis
Processing Record 46 of Set 32 | garden city
Processing Record 47 of Set 32 | oktyabrskoye
Processing Record 48 of Set 32 | inongo
Processing Record 49 of Set 32 | ayan
Processing Record 50 of Set 32 | copperas cove
Processing Record 1 of Set 33 | chagda
City not found. Skipping...
Processing Record 2 of Set 33 | serenje
Processing Record 3 of Set 33 | seymchan
Processing Record 4 of Set 33 | saint george
Processing Record 5 of Set 33 | uvalde
Processing Record 6 of Set 33 | pokosnoye
Processing Record 7 of Set 33 | khandyga
Processing Record 8 of Set 33 | klaksvik
Processing Record 9 of Set 33 | skibbereen
Processing Record 10 of Set 33 | aztec
Processing Record 11 of Set 33 | krasnyy
Processing Record 12 of Set 33 | esmeraldas
Processing Record 13 of Set 33 | ghanzi
Processing Record 14 of Set 33 | agadez
Processing Record 15 of Set 33 | aklavik
Processing Record 16 of Set 33 | colesberg
Processing Record 17 of Set 33 | gondar
Processing Record 18 of Set 33 | brae
Processing Record 19 of Set 33 | junction city
Processing Record 20 of Set 33 | hasaki
Processing Record 21 of Set 33 | nanortalik
Processing Record 22 of Set 33 | albertville
Processing Record 23 of Set 33 | den helder
Processing Record 24 of Set 33 | huaral
Processing Record 25 of Set 33 | mandalay
Processing Record 26 of Set 33 | pocao de pedras
Processing Record 27 of Set 33 | ullapool
Processing Record 28 of Set 33 | pacasmayo
Processing Record 29 of Set 33 | peterhead
Processing Record 30 of Set 33 | kochevo
Processing Record 31 of Set 33 | puri
Processing Record 32 of Set 33 | tsihombe
City not found. Skipping...
Processing Record 33 of Set 33 | pokhara
Processing Record 34 of Set 33 | fort-shevchenko
Processing Record 35 of Set 33 | manolas
Processing Record 36 of Set 33 | kemi
Processing Record 37 of Set 33 | malanje
Processing Record 38 of Set 33 | puntarenas
Processing Record 39 of Set 33 | one hundred mile house
City not found. Skipping...
Processing Record 40 of Set 33 | bayir
Processing Record 41 of Set 33 | warqla
City not found. Skipping...
Processing Record 42 of Set 33 | strausberg
Processing Record 43 of Set 33 | walvis bay
Processing Record 44 of Set 33 | luderitz
Processing Record 45 of Set 33 | nova olimpia
Processing Record 46 of Set 33 | sicuani
Processing Record 47 of Set 33 | san quintin
Processing Record 48 of Set 33 | dengzhou
Processing Record 49 of Set 33 | uruzgan
Processing Record 50 of Set 33 | radom
Processing Record 1 of Set 34 | madera
Processing Record 2 of Set 34 | quatre cocos
Processing Record 3 of Set 34 | kahului
Processing Record 4 of Set 34 | coquimbo
Processing Record 5 of Set 34 | te anau

Processing Record 6 of Set 34 | san cristobal
Processing Record 7 of Set 34 | acapulco
Processing Record 8 of Set 34 | fort saint john
City not found. Skipping...
Processing Record 9 of Set 34 | milkovo
Processing Record 10 of Set 34 | rabat
Processing Record 11 of Set 34 | martil
Processing Record 12 of Set 34 | rio grande
Processing Record 13 of Set 34 | tessalit
Processing Record 14 of Set 34 | halalo
City not found. Skipping...
Processing Record 15 of Set 34 | saldanha
Processing Record 16 of Set 34 | morgan city
Processing Record 17 of Set 34 | soloneshnoye
Processing Record 18 of Set 34 | humaita
Processing Record 19 of Set 34 | pingliang
Processing Record 20 of Set 34 | kenai
Processing Record 21 of Set 34 | mimongo
Processing Record 22 of Set 34 | maumere
Processing Record 23 of Set 34 | shieli
Processing Record 24 of Set 34 | codrington
Processing Record 25 of Set 34 | nouakchott
Processing Record 26 of Set 34 | kangaba
Processing Record 27 of Set 34 | lillers
Processing Record 28 of Set 34 | russell
Processing Record 29 of Set 34 | loiza
Processing Record 30 of Set 34 | oranjemund
Processing Record 31 of Set 34 | san jose
Processing Record 32 of Set 34 | mount gambier
Processing Record 33 of Set 34 | nexo
Processing Record 34 of Set 34 | duluth
Processing Record 35 of Set 34 | samarai
Processing Record 36 of Set 34 | pakaur
Processing Record 37 of Set 34 | virden
Processing Record 38 of Set 34 | tiruvottiyur
City not found. Skipping...
Processing Record 39 of Set 34 | kieta
Processing Record 40 of Set 34 | vaitupu
City not found. Skipping...
Processing Record 41 of Set 34 | rondonopolis
Processing Record 42 of Set 34 | kendari
Processing Record 43 of Set 34 | portland
Processing Record 44 of Set 34 | nizhnevartovsk
Processing Record 45 of Set 34 | tabou
Processing Record 46 of Set 34 | jiayuguan
Processing Record 47 of Set 34 | sataua
City not found. Skipping...
Processing Record 48 of Set 34 | patacamaya
Processing Record 49 of Set 34 | manitouwadge
-----------------------------
Data Retrieval Complete
-----------------------------

In [89]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,Carnarvon,-24.8667,113.6333,75.99,63,0,20.22,AU,2022-02-08 20:14:04,NaN
1,Nikolskoye,59.7035,30.7861,28.29,96,100,4.81,RU,2022-02-08 20:14:05,NaN
2,Fortuna,40.5982,-124.1573,61.93,70,0,1.01,US,2022-02-08 20:13:00,NaN
3,Kavieng,-2.5744,150.7967,80.91,80,100,8.30,PG,2022-02-08 20:14:05,NaN
4,Kaitangata,-46.2817,169.8464,56.25,92,100,7.20,NZ,2022-02-08 20:14:06,NaN
...,...,...,...,...,...,...,...,...,...,...
1642,Nizhnevartovsk,60.9344,76.5531,-8.99,84,20,7.00,RU,NaN,few clouds
1643,Tabou,4.4230,-7.3528,79.03,86,3,8.90,CI,NaN,clear sky
1644,Jiayuguan,39.8167,98.3000,14.18,59,26,4.99,CN,NaN,scattered clouds
1645,Patacamaya,-17.2333,-67.9167,52.79,67,97,7.18,BO,NaN,overcast clouds
1646,Manitouwadge,49.1215,-85.8403,27.32,91,100,10.04,CA,NaN,overcast clouds

In [90]:
city_data_df.dropna()

Empty DataFrame
Columns: [City, Lat, Lng, Max Temp, Humidity, Cloudiness, Wind Speed, Country, Date, Current Description]
Index: []

In [81]:
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,Carnarvon,-24.8667,113.6333,75.99,63,0,20.22,AU,2022-02-08 20:14:04,NaN
1,Nikolskoye,59.7035,30.7861,28.29,96,100,4.81,RU,2022-02-08 20:14:05,NaN
2,Fortuna,40.5982,-124.1573,61.93,70,0,1.01,US,2022-02-08 20:13:00,NaN
3,Kavieng,-2.5744,150.7967,80.91,80,100,8.30,PG,2022-02-08 20:14:05,NaN
4,Kaitangata,-46.2817,169.8464,56.25,92,100,7.20,NZ,2022-02-08 20:14:06,NaN
...,...,...,...,...,...,...,...,...,...,...
1093,Nizhnevartovsk,60.9344,76.5531,-8.99,84,0,8.99,RU,NaN,clear sky
1094,Tabou,4.4230,-7.3528,79.03,86,3,8.90,CI,NaN,clear sky
1095,Jiayuguan,39.8167,98.3000,14.18,59,26,4.99,CN,NaN,scattered clouds
1096,Patacamaya,-17.2333,-67.9167,52.79,67,97,7.18,BO,NaN,overcast clouds
1097,Manitouwadge,49.1215,-85.8403,27.32,91,100,10.04,CA,NaN,overcast clouds

In [87]:
city_data_df.isnull().sum()

City                   0.0
Lat                    0.0
Lng                    0.0
Max Temp               0.0
Humidity               0.0
Cloudiness             0.0
Wind Speed             0.0
Country                0.0
Date                   0.0
Current Description    0.0
dtype: float64

In [84]:
city_data_df = city_data_df.dropna()

In [93]:
city_data_df=city_data_df.drop('Date', 1)

C:\Users\m164363\AppData\Local\Temp/ipykernel_16400/1678556067.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  city_data_df=city_data_df.drop('Date', 1)

In [94]:
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,Carnarvon,-24.8667,113.6333,75.99,63,0,20.22,AU,NaN
1,Nikolskoye,59.7035,30.7861,28.29,96,100,4.81,RU,NaN
2,Fortuna,40.5982,-124.1573,61.93,70,0,1.01,US,NaN
3,Kavieng,-2.5744,150.7967,80.91,80,100,8.30,PG,NaN
4,Kaitangata,-46.2817,169.8464,56.25,92,100,7.20,NZ,NaN
...,...,...,...,...,...,...,...,...,...
1642,Nizhnevartovsk,60.9344,76.5531,-8.99,84,20,7.00,RU,few clouds
1643,Tabou,4.4230,-7.3528,79.03,86,3,8.90,CI,clear sky
1644,Jiayuguan,39.8167,98.3000,14.18,59,26,4.99,CN,scattered clouds
1645,Patacamaya,-17.2333,-67.9167,52.79,67,97,7.18,BO,overcast clouds
1646,Manitouwadge,49.1215,-85.8403,27.32,91,100,10.04,CA,overcast clouds

In [96]:
city_data_df = city_data_df.dropna()

In [97]:
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
549,Carnarvon,-24.8667,113.6333,73.47,73,0,10.36,AU,clear sky
550,Nikolskoye,59.7035,30.7861,28.80,96,100,4.81,RU,snow
551,Fortuna,40.5982,-124.1573,62.85,71,0,10.36,US,clear sky
552,Kavieng,-2.5744,150.7967,82.69,78,100,9.28,PG,light rain
553,Kaitangata,-46.2817,169.8464,59.14,85,100,9.91,NZ,overcast clouds
...,...,...,...,...,...,...,...,...,...
1642,Nizhnevartovsk,60.9344,76.5531,-8.99,84,20,7.00,RU,few clouds
1643,Tabou,4.4230,-7.3528,79.03,86,3,8.90,CI,clear sky
1644,Jiayuguan,39.8167,98.3000,14.18,59,26,4.99,CN,scattered clouds
1645,Patacamaya,-17.2333,-67.9167,52.79,67,97,7.18,BO,overcast clouds
1646,Manitouwadge,49.1215,-85.8403,27.32,91,100,10.04,CA,overcast clouds

In [98]:
# Create the output file (CSV).
output_data_file = "WeatherPy_Database.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")